name = "Migel Alvarez"
author = "Migel Alvarez"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3144ccf2be83459d664505376d6c5cdde2d3e6ccbad3ca8e1f29199acd4c7f09"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
