name = "modapcak"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7399245222d014bd1aeed9eadd297bff28a4d6c8abd0fabcfa45b6b587267560"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"
